import React, { createContext, useContext, useState, useEffect } from 'react';

const TRANSLATIONS = {
  en: {
    dir: 'ltr',
    lang: 'en',
    appName: 'Jordan Aviation',
    appSubtitle: 'ORG STRUCTURE',
    nav: {
      home: 'Home',
      orgChart: 'Org Chart',
      departments: 'Departments',
      directory: 'Directory',
      contents: 'Contents',
      search: 'Search',
      technical: 'Technical',
      nonTechnical: 'Non-Technical',
      searchPlaceholder: 'Find position or dept...',
    },
    hero: {
      badge: 'CARC • IATA • ICAO Compliant',
      title1: 'Jordan Aviation Airline',
      title2: 'Organization Structure System',
      subtitle: 'A comprehensive organizational framework covering all departments, positions, job descriptions, and standard operating procedures for Jordan Aviation Airline.',
      viewChart: 'View Org Chart →',
      downloadPDF: '⬇ Download PDF Booklet',
      printBooklet: '🖨️ Print Full Booklet',
    },
    stats: {
      departments: 'Departments',
      positions: 'Positions',
      sops: 'SOPs',
      compliant: 'Compliant',
    },
    sections: {
      executive: 'Executive Leadership',
      technical: 'Technical Departments',
      nonTechnical: 'Non-Technical Departments',
      download: 'Download & Share',
    },
    directory: {
      title: 'Employee Directory',
      subtitle: 'All positions across all 16 departments. Search, filter, and click any position to view the full job description.',
      searchPlaceholder: 'Search by title, department...',
      filterDept: 'All Departments',
      filterCat: 'All Categories',
      filterLevel: 'All Levels',
      sortBy: 'Sort by',
      sortDept: 'Department',
      sortTitle: 'Position Title',
      sortLevel: 'Seniority Level',
      tableTitle: 'Position Title',
      tableDept: 'Department',
      tableCategory: 'Category',
      tableLevel: 'Level',
      tableReports: 'Reports To',
      tableAction: 'View JD',
      noResults: 'No positions match your search.',
      totalPositions: 'Total Positions',
      clickToView: 'Click any row to view the full job description',
    },
    dept: {
      chart: '🗂 Org Chart',
      overview: '📋 Overview',
      positions: '👥 Positions',
      sops: '📄 SOPs',
      backHome: '← Back to Home',
      print: '🖨️ Print Department',
      deptHead: 'Department Head',
      quickStats: 'Quick Stats',
      allPositions: 'All Positions',
      totalPositions: 'Total Positions',
      sopsAvailable: 'SOPs Available',
      reportsTo: 'Reports To',
      category: 'Category',
      viewJD: 'View Job Description',
      chartTitle: 'Org Chart',
      chartDesc: 'Reporting hierarchy for all {n} positions. Click any node to view the full job description.',
      positionSummary: 'Position Summary',
      reportingHierarchy: 'Reporting hierarchy',
      staffPositions: 'Staff Positions',
    },
    common: {
      reportsTo: 'Reports to',
      viewSOP: 'View SOP',
      viewJD: 'View Job Description',
      close: '✕ Close',
      purpose: 'Purpose',
      responsibilities: 'Key Responsibilities',
      qualifications: 'Qualifications',
      experience: 'Experience Required',
      kpis: 'Key Performance Indicators',
      sopScope: 'Scope',
      sopResponsibilities: 'Responsibilities',
      sopProcedures: 'Step-by-Step Procedures',
      sopSafety: 'Safety Requirements',
      sopCarc: 'CARC Compliance',
      carcCompliant: 'CARC Compliant',
      technical: 'technical',
      nonTechnical: 'non-technical',
    },
    levels: {
      cSuite: 'C-Suite',
      vp: 'VP / Head',
      director: 'Director',
      manager: 'Manager',
      officer: 'Officer',
      pilot: 'Pilot / Crew',
      staff: 'Staff',
    },
  },
  ar: {
    dir: 'rtl',
    lang: 'ar',
    appName: 'الأردن للطيران',
    appSubtitle: 'الهيكل التنظيمي',
    nav: {
      home: 'الرئيسية',
      orgChart: 'الهيكل التنظيمي',
      departments: 'الأقسام',
      directory: 'دليل الموظفين',
      contents: 'المحتويات',
      search: 'بحث',
      technical: 'تقني',
      nonTechnical: 'غير تقني',
      searchPlaceholder: 'ابحث عن منصب أو قسم...',
    },
    hero: {
      badge: 'متوافق مع CARC • IATA • ICAO',
      title1: 'شركة الأردن للطيران',
      title2: 'نظام الهيكل التنظيمي',
      subtitle: 'إطار تنظيمي شامل يغطي جميع الأقسام والمناصب والأوصاف الوظيفية وإجراءات التشغيل القياسية لشركة الأردن للطيران.',
      viewChart: 'عرض الهيكل التنظيمي ←',
      downloadPDF: '⬇ تحميل الكتيب PDF',
      printBooklet: '🖨️ طباعة الكتيب الكامل',
    },
    stats: {
      departments: 'قسم',
      positions: 'منصب',
      sops: 'إجراء',
      compliant: 'متوافق',
    },
    sections: {
      executive: 'القيادة التنفيذية',
      technical: 'الأقسام التقنية',
      nonTechnical: 'الأقسام غير التقنية',
      download: 'تحميل ومشاركة',
    },
    directory: {
      title: 'دليل الموظفين',
      subtitle: 'جميع المناصب عبر الأقسام الـ16. ابحث وصفّ وانقر على أي منصب لعرض الوصف الوظيفي الكامل.',
      searchPlaceholder: 'ابحث بالمسمى الوظيفي أو القسم...',
      filterDept: 'جميع الأقسام',
      filterCat: 'جميع الفئات',
      filterLevel: 'جميع المستويات',
      sortBy: 'ترتيب حسب',
      sortDept: 'القسم',
      sortTitle: 'المسمى الوظيفي',
      sortLevel: 'المستوى الوظيفي',
      tableTitle: 'المسمى الوظيفي',
      tableDept: 'القسم',
      tableCategory: 'الفئة',
      tableLevel: 'المستوى',
      tableReports: 'يرفع إلى',
      tableAction: 'عرض',
      noResults: 'لا توجد مناصب تطابق بحثك.',
      totalPositions: 'إجمالي المناصب',
      clickToView: 'انقر على أي صف لعرض الوصف الوظيفي الكامل',
    },
    dept: {
      chart: '🗂 الهيكل التنظيمي',
      overview: '📋 نظرة عامة',
      positions: '👥 المناصب',
      sops: '📄 الإجراءات',
      backHome: 'العودة للرئيسية →',
      print: '🖨️ طباعة القسم',
      deptHead: 'رئيس القسم',
      quickStats: 'إحصاءات سريعة',
      allPositions: 'جميع المناصب',
      totalPositions: 'إجمالي المناصب',
      sopsAvailable: 'الإجراءات المتاحة',
      reportsTo: 'يرفع إلى',
      category: 'الفئة',
      viewJD: 'عرض الوصف الوظيفي',
      chartTitle: 'الهيكل التنظيمي',
      chartDesc: 'التسلسل الهرمي لجميع {n} منصباً. انقر على أي عقدة لعرض الوصف الوظيفي الكامل.',
      positionSummary: 'ملخص المناصب',
      reportingHierarchy: 'التسلسل الهرمي',
      staffPositions: 'مناصب الموظفين',
    },
    common: {
      reportsTo: 'يرفع إلى',
      viewSOP: 'عرض الإجراء',
      viewJD: 'عرض الوصف الوظيفي',
      close: '✕ إغلاق',
      purpose: 'الغرض',
      responsibilities: 'المسؤوليات الرئيسية',
      qualifications: 'المؤهلات',
      experience: 'الخبرة المطلوبة',
      kpis: 'مؤشرات الأداء الرئيسية',
      sopScope: 'النطاق',
      sopResponsibilities: 'المسؤوليات',
      sopProcedures: 'الإجراءات خطوة بخطوة',
      sopSafety: 'متطلبات السلامة',
      sopCarc: 'امتثال CARC',
      carcCompliant: 'متوافق مع CARC',
      technical: 'تقني',
      nonTechnical: 'غير تقني',
    },
    levels: {
      cSuite: 'الإدارة العليا',
      vp: 'نائب الرئيس',
      director: 'مدير',
      manager: 'مشرف',
      officer: 'مسؤول',
      pilot: 'طيار / طاقم',
      staff: 'موظف',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('jav-lang') || 'en');

  useEffect(() => {
    localStorage.setItem('jav-lang', lang);
    document.documentElement.dir = TRANSLATIONS[lang].dir;
    document.documentElement.lang = lang;
  }, [lang]);

  const t = TRANSLATIONS[lang];
  const toggle = () => setLang(l => l === 'en' ? 'ar' : 'en');

  return (
    <LanguageContext.Provider value={{ lang, t, toggle, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
